//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportInvent
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public int hum_id { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string patronim { get; set; }
        public string email { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string phone_num { get; set; }
        public int pass_ser { get; set; }
        public int pass_num { get; set; }
        public System.DateTime birthday { get; set; }
        public Nullable<System.DateTime> last_enter { get; set; }
        public Nullable<int> type_enter_id { get; set; }
        public int gender_id { get; set; }
    
        public virtual gender gender { get; set; }
        public virtual human human { get; set; }
        public virtual type_enter type_enter { get; set; }
    }
}
